## The Python Programming Language:
## Functions
    

add_numbers is a function that takes two numbers and adds them together

In [78]:
def  add_numbers(x, y):
    return x + y

add_numbers(1,2)

3

add_numbers updated to take an optional 3rd parameter, using print allows printing of multiple expresions within a single cell

In [79]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
        
print(add_numbers(1,2))
print(add_numbers(1,2,3))

3
6


add_numbers updates to take an optional flag parameter

In [80]:
def add_numbers(x,y,z=None, flag=False):
    if(flag):
        print('Flag is true!')
    if(z==None):
        return x + y
    else:
        return x+y+z
    
print(add_numbers(1,5,flag=True))

Flag is true!
6


##Assing Function add_numbers to variable a

In [81]:
def add_numbers(x,y):
    return x+y
a= add_numbers
a(1,2)

3

## The Python Programing Language: Types and Sequences

Use type to return the object´s type

In [82]:
type('This is a string')

str

In [83]:
type(None)

NoneType

In [84]:
type(1)

int

In [85]:
type(1.0)

float

In [86]:
type(add_numbers)

function

Tuples are an inmutable data structure (cannot be altered). A Tuple in math is a ordened list of objects.

In [87]:
x=(1, 'a', 2, 'b')
type(x)

tuple

Lists are mutable data structure

In [88]:
x = [1, 'a', 2, 'b']
type(x)

list

Use append to append an object to a list. Append --> adjuntar

In [89]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


This is an example of  how to loop through each item in the list

In [90]:
for item in x:
    print(item)

1
a
2
b
3.3


Or using indexing operator. Where len() is a function that eturns the number of elements in a list

In [91]:
i=0
while ( i != len(x) ):
    print(x[i])
    i=i+1

1
a
2
b
3.3


Use + to concatenate lists

In [92]:
[1,2] + [3,4]

[1, 2, 3, 4]

Use * to repeat lists

In [93]:
[1]*3

[1, 1, 1]

Use the in operator to check if something is inside a list

In [94]:
1 in [1,2,3]

True

Now let's look a strings. Use the bracket notation to slice a string

In [95]:
x ='This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end caracter
print(x[0:2])

T
T
Th


This will return the last element of the string

In [96]:
x[-1]

'g'

In [97]:
x[-4:-2]

'ri'

This is a slice from the beginning of the string and stopping before the 3rd element.

In [98]:
x[:3]

'Thi'

And this is a slice starting from the  4th element of the string and going all the way to the end

In [99]:
x[3:]

's is a string'

In [100]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)

Christopher Brooks
ChristopherChristopherChristopher
True


split returns a list of all the words in a string, or a list split on a specific character

In [101]:
firstname = 'Christpher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] #[-1] selects the last element of the list
print(firstname)
print(lastname)

Christpher
Brooks


Make sure you convert objects to strings before concatenating

In [102]:
#'Chris' + 2

In [103]:
'Chris' + str(2)

'Chris2'

Dictionaries associate keys with values. 

In [104]:
x = {'Christopher Brooks': 'brookch@umich.edu', 'Bill Gates':'billg@microsoft.com', 'Mario Rosas':'malttz15@gmail.com'}
x['Mario Rosas'] # Retrieve a value by using the indexing operator

'malttz15@gmail.com'

In [105]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']


Iterate over all of the keys:

In [106]:
for name  in x:
    print(name)

Christopher Brooks
Bill Gates
Mario Rosas
Kevyn Collins-Thompson


Now notice specially the part of -->   print(x[name]) 

In [107]:
for name  in x:
    print(x[name])

brookch@umich.edu
billg@microsoft.com
malttz15@gmail.com
None


Iterate over all of the values

In [108]:
for email in x.values():
    print(email)

brookch@umich.edu
billg@microsoft.com
malttz15@gmail.com
None


Iterate over all of the items in the list:

In [109]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brookch@umich.edu
Bill Gates
billg@microsoft.com
Mario Rosas
malttz15@gmail.com
Kevyn Collins-Thompson
None


You can unpack a sequence into different variables:

In [110]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [111]:
fname

'Christopher'

In [112]:
lname

'Brooks'

In [113]:
email

'brooksch@umich.edu'

Make sure the number of values  you are unpacking matches the number of variabñes being assigned

In [114]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

## The Python Programing Language: More on Strings

In [ ]:
print('Chris' + 2)

In [ ]:
print('Chris' + str(2))

Python has a built in method for convenient string fromatting

In [ ]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

## Reading and Writing a CSV files

<br>
Let's import our datafile mpg.csv, wich contains fuel economy  data for 243 cars

* mpg : miles per galon
* class : car classification
* city : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premiun, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year



In [ ]:
import csv 

%precision 2

with open('mpg.csv') as cvsfile:
    mpg = list(csv.DictReader(cvsfile))
    
mpg[:3] # The first three dictionaries in our list

csv.Dictreader has read in each row of our csv file as a dictionary. len() shows that our list is comprised of 234 dictionaries

In [ ]:
len(mpg)

keys gives us the column names of our csv

In [ ]:
mpg[0].keys()

This is how to find the average cty fuel economy across all cars. All vales in the dictionaries are strings, so we need to convert to float

In [ ]:
sum(float(d['cty']) for d in mpg) / len (mpg)

Similarly  this is how to find the average hwy fuel economy across all cars

In [ ]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

In [ ]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

Here´s a more complex example where we are grouping the cars by a number of cylinder, and finding the average cty mpg for each group

In [ ]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: #if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')
    
CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl


Use set to return the unique values for the class types in our dataset.

In [ ]:
vehicleclass = set(d['class'] for d in mpg) #what are the class types
vehicleclass

And here's an example of how find the average hwy mpg for each class of vehicle in our dataset

In [ ]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

## The Python Programming:Dates and Times
    

In [ ]:
import datetime as dt
import time as tm

time returns the curent time in seconds since de Epoch.(January 1st, 1970)

In [ ]:
tm.time()

Convert the timestamp to datetime

In [ ]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

Handy datetime attributes:

In [ ]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

timedelta is a duration expressing the difference between two dates

In [ ]:
delta = dt.timedelta(days = 335) #create a timedelta of 100 days
delta

date.today returns the current local date

In [ ]:
today = dt.date.today()

In [ ]:
today - delta # the date 100 days ago

In [ ]:
today > today-delta # compare dates

## The Python Programming Language: Objects and map()

An example of a class in python:

In [ ]:
class Person:
    department = 'School of infromation' # a class variable
    
    def set_name(self, new_name): # a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [ ]:
person = Person ()
person.set_name('Christopher Brooks')
person.set_location('Ann arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

In [ ]:
class Objectd: 
    kind = 'Car' # a class variable
    
    def set_enginename(self, new_enginename): # a method
        self.enginename = new_enginename
    def set_brand(self, new_brand):
        self.brand = new_brand

In [115]:
objectd = Objectd ()
objectd.set_enginename('db9')
objectd.set_brand('Aston Martin')
print('{} belongs to {} and is a sport {}'.format(objectd.enginename, objectd.brand, objectd.kind))

db9 belongs to Aston Martin and is a sport Car


Here's an example of mapping the min funtion between two lists

In [116]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
store3 = [8.00, 15.10, 10.34, 5.01]
cheapest = map(min, store1, store3)
cheapest

In [117]:
for item in cheapest:
    print(item)

8.0
11.0
10.34
2.34


In [118]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
  tittle = person.split()[0]
  lastname = person.split()[-1]
  return '{} {}'.format(tittle, lastname) 

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

## The Python Programming Language: Lambda and List Comprehensions

Here´s an example of lambda that takes in three parameters and add the first two

In [119]:
my_function = lambda a, b, c, : a + c

In [120]:
my_function(1, 2, 3)

4

In [121]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x:x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(split_title_and_name, people))

True
True
True
True


True

let´s iterate from 0 to 999 and return the even numbers

In [122]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

let´s iterate from 0 to 999 and return the odd numbers

In [123]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 1:
        my_list.append(number)
my_list

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239,
 241,
 243,
 245,
 247,
 249,
 251,
 253,
 255,
 257,
 259,
 261,
 263,
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 299,
 301,
 303,
 305,
 307,
 309,
 311,
 313,
 315,
 317,
 319,
 321,
 323,
 325,
 327,
 329,
 331,
 333,
 335,
 337,
 339,
 341,
 343,
 345,
 347,
 349,
 351,

let´s iterate from 0 to 999 and return the multiples of 6

In [124]:
my_list = []
for number in range(0, 1000):
    if number % 6 == 0:
        my_list.append(number)
my_list

[0,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 60,
 66,
 72,
 78,
 84,
 90,
 96,
 102,
 108,
 114,
 120,
 126,
 132,
 138,
 144,
 150,
 156,
 162,
 168,
 174,
 180,
 186,
 192,
 198,
 204,
 210,
 216,
 222,
 228,
 234,
 240,
 246,
 252,
 258,
 264,
 270,
 276,
 282,
 288,
 294,
 300,
 306,
 312,
 318,
 324,
 330,
 336,
 342,
 348,
 354,
 360,
 366,
 372,
 378,
 384,
 390,
 396,
 402,
 408,
 414,
 420,
 426,
 432,
 438,
 444,
 450,
 456,
 462,
 468,
 474,
 480,
 486,
 492,
 498,
 504,
 510,
 516,
 522,
 528,
 534,
 540,
 546,
 552,
 558,
 564,
 570,
 576,
 582,
 588,
 594,
 600,
 606,
 612,
 618,
 624,
 630,
 636,
 642,
 648,
 654,
 660,
 666,
 672,
 678,
 684,
 690,
 696,
 702,
 708,
 714,
 720,
 726,
 732,
 738,
 744,
 750,
 756,
 762,
 768,
 774,
 780,
 786,
 792,
 798,
 804,
 810,
 816,
 822,
 828,
 834,
 840,
 846,
 852,
 858,
 864,
 870,
 876,
 882,
 888,
 894,
 900,
 906,
 912,
 918,
 924,
 930,
 936,
 942,
 948,
 954,
 960,
 966,
 972,
 978,
 984,
 990,
 996]

Now the same thing but with a list comprehension

In [125]:
my_list = [number for number in range(0, 1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

## The Python Programming Language: Numerical Python (NumPy)

In [126]:
import numpy as np


### Creating Arrays

Create a list and convert it to a numpy array

In [127]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

Or just pass in a list directly

In [128]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [129]:
j = np.array([4, 5, 6, 8, 10])
j

array([ 4,  5,  6,  8, 10])

Pass in a list of lists to create a multidimensional array

In [130]:
m = np.array([[6,7,8,9], [13,10,11,12], [0,1,2,3]])
m

array([[ 6,  7,  8,  9],
       [13, 10, 11, 12],
       [ 0,  1,  2,  3]])

Use the shape method to find the dimension of the array. (rows, columns)

In [131]:
m.shape

(3, 4)

`arange` returns evenly spaced values within a given interval

In [132]:
n = np.arange(0, 30, 2) #start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

 `reshape` returns an array with same data with a new shape

In [133]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [134]:
n.shape

(3, 5)

`linspace` returns evenly spaced numbers over a specified interval

In [135]:
o = np.linspace(0,4,9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

`resize` changes the shape and size of array in-place

In [136]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [137]:
o = o.reshape(3, 3) # reshape array to be 3x5
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

`ones` returns a new array of given shape and type, filled with ones

In [138]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

`zeros` returns a new array of given shape and type, filled with ones

In [139]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

`eye` returns a 2-D array with ones on diagonal and zeros elsewhere

In [140]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

`diag` extracs a diagonal or constructs a diagonal array

In [141]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [142]:
np.diag(j)

array([[ 4,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

Create an array using repeating list(or see np.tile)

In [143]:
np.array([1, 2, 3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [144]:
np.tile([1,2,3], 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Repeat elements of an array unsing `repeat`

In [145]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combining Arrays

In [146]:
p = np.ones([2, 3], float)
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [147]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

Use `vstack`to stack arrays in sequence vertically (column wise). Stack --> apilar

In [148]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Use `hstack`to stack arrays in sequence horizontally (column wise). Stack --> apilar

In [149]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### Operations

Use `+, -, *, /` and `**` to perform element wise addition, subtraction, multiplication, division and power. Where `**` is to get an exponential operation.

In [150]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5 7 9]    
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3] 

[5 7 9]
[-3 -3 -3]


In [151]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4 10 18]    
print(x / y) # elementwise division        [1 2 3] / [4 5 6] = [0.25 0.4 0.5] 

[ 4 10 18]
[0.25 0.4  0.5 ]


In [152]:
print(x**2) # elementwise power [1 2 3] ^ 2 = [1 4 9]

[1 4 9]


### Dot Product

<br>
$ \begin{bmatrix}
    x_1 & x_2 & x_3 
  \end{bmatrix}
   \cdot 
  \begin{bmatrix}
    y_1 \\ y_2 \\ y_3
  \end{bmatrix}
  = x_1 y_1 + x_2 y_2 + x_3 y_3$


In [157]:
x.dot(y) # dot product 1*4 + 2*5 + 3*6 

32

In [158]:
print(len(z)) # Number of rows of array

TypeError: object of type 'numpy.int32' has no len()

Let´s look at transposing arrays. Transposing permutes the dimension of array.

In [159]:
z = np.array([y, y**2, y**3])
z

array([[  4,   5,   6],
       [ 16,  25,  36],
       [ 64, 125, 216]])

In [160]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

The shape of array z is (2,3) before transposing.

In [161]:
z.shape

(2, 3)

Use `.T` to get the transpose

In [162]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

The number of rows has swapped with the number of columns. Swap --> intercambiar

In [163]:
z.T.shape

(3, 2)

Use `.dtype` to see the data type of the elements in the array

In [164]:
z.dtype

dtype('int32')

Use `.astype` to cast to a specific type

In [165]:
z = z.astype('f')
z.dtype

dtype('float32')

### Math Functions

Numpy has many built in math functions that can be performed on arrays

In [166]:
a = np.array([-4, -2, 1, 3, 5])

In [167]:
a.sum()

3

In [168]:
a.max()

5

In [169]:
a.min()

-4

Mean is equal to the average

In [170]:
a.mean()

0.6

In [171]:
a.std()

3.2619012860600183

`argmax` and `argmin` return the index of the maximun and minimun  values in the array. In this case the index is the value of the pocision that each value have, ever the index starts at 0 in this case `a=[-4, -2, 1, 3, 5]` so `-4 is index 0` `-2 --> 1` `1--> 2` `3--> 3` `5--> 4`

In [172]:
a.argmax()

4

In [173]:
a.argmin()

0

### Indexin / Slicing

in the next funtion the numbers are incremented with a distance of the odd numbers

In [174]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

Use bracket notation to get the value at a specific index, remember that the indexing starts at 0 and the `-1` represent the last value of the array

In [175]:
s[0], s[4], s[-1]

(0, 16, 144)

Use `:` to indicate a range. array[start:stop]
    
Leaving `start` or `stop` empty will default to the beginning/end of the array

In [176]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

Use Negatives to count from the back

In [177]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [178]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

Let´s look a multidimensional Array

In [179]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use the bracket notation to slice: array[row, column]. So you´re getting the value in this coordinates starting count the rows and columns from 0

In [180]:
r[2, 2]

14

And use `:` to select a range of rows or columns

In [181]:
r[3, 3:6]

array([21, 22, 23])

Here we are selecting all the rows up  to (and not including) row 2, and all the columns up to (and not including) the last column

In [182]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

This is a slice of the last row and only every other element.

In [183]:
r[-1, ::2]

array([30, 32, 34])

We can also perform conditional indexing. Here we´re selecting values from the array that are greater than 30. (Also see np.where)

In [184]:
r[r > 30]

array([31, 32, 33, 34, 35])

Here were assigning all values in the array that are greater than 30 to the values of 30

In [185]:
r[r > 29] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [186]:
r[r > 30]

array([], dtype=int32)

### Copying Data

Be careful with copting and modifying arrays in NumPy!

r2 is a slice of r

In [187]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Set this slice values to zero (`[:]` selects the entire array)

In [188]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

r has also been changed!

In [189]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

To avoid this, use `r.copy` to create a copy that will not affect the original array

In [190]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now when r_copy is modified, r will not be changed.

In [191]:
r_copy[:] = 10
print(r_copy, '\n\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 


[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating Over Arrays

Let´s create a new 4 by 3 array of random numbers 0-9

In [192]:
test = np.random.randint(0, 10, (4,3))
test

array([[6, 8, 0],
       [6, 6, 5],
       [4, 2, 7],
       [0, 8, 6]])

Iterate by row:

In [193]:
for row in test:
    print(row)

[6 8 0]
[6 6 5]
[4 2 7]
[0 8 6]


Iterate by index

In [194]:
for i in range(len(test)):
    print (test[i])

[6 8 0]
[6 6 5]
[4 2 7]
[0 8 6]


Iterate by row and index

In [195]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [6 8 0]
row 1 is [6 6 5]
row 2 is [4 2 7]
row 3 is [0 8 6]


Use `zip` to iterate over multiple iterables

In [196]:
test2= test**2
test2

array([[36, 64,  0],
       [36, 36, 25],
       [16,  4, 49],
       [ 0, 64, 36]], dtype=int32)

In [197]:
for i, j in zip(test, test2):
    print(i,'+', j, '=', i+j)

[6 8 0] + [36 64  0] = [42 72  0]
[6 6 5] + [36 36 25] = [42 42 30]
[4 2 7] + [16  4 49] = [20  6 56]
[0 8 6] + [ 0 64 36] = [ 0 72 42]
